const { GoogleGenerativeAI } = require('@google/generative-ai');

// Fallback Mock generator when GEMINI_API_KEY is not defined
const getMockOutline = (prompt, slideCount = 5) => {
  console.log(`🤖 [AI Mock] Generating mock presentation for: "${prompt}" (${slideCount} slides)`);
  const topics = ['Introduction', 'Market Overview', 'The Problem', 'Our Solution', 'Key Features', 'Business Model', 'Future Vision'];
  const slides = [];

  for (let i = 0; i < Math.min(slideCount, topics.length); i++) {
    let layout = 'bullets';
    let icon = 'Presentation';
    let content = [
      `Key insight about ${prompt} on slide ${i + 1}`,
      `Secondary point illustrating the scope and impact`,
      `Supporting details and metric indicators`
    ];

    if (i === 0) {
      layout = 'title';
      icon = 'Presentation';
      content = [`A comprehensive overview of ${prompt}`, `Generated by AI Presentation Builder`];
    } else if (i === 1) {
      layout = 'stats';
      icon = 'TrendingUp';
      content = [`85%`, `Market growth year over year`, `Current industry expansion index`];
    } else if (i === 3) {
      layout = 'columns';
      icon = 'Columns';
      content = [`Point A: Rapid deployment`, `Point B: Cloud integration`, `Point C: Direct user support`];
    } else if (i === 4) {
      layout = 'timeline';
      icon = 'Clock';
      content = [`Phase 1: Alpha Launch`, `Phase 2: User Hydration`, `Phase 3: Direct Scaling`];
    }

    slides.push({
      title: `${topics[i]} - ${prompt}`,
      content,
      layout,
      icon,
      note: `Speaker note detailing slide ${i + 1} content about ${prompt}. Focus on speaking clearly and presenting visual cards.`
    });
  }

  return {
    title: `${prompt.charAt(0).toUpperCase() + prompt.slice(1)} Presentation`,
    slides
  };
};

// Initialize Gemini Client safely
let aiClient = null;
if (process.env.GEMINI_API_KEY) {
  // Setup Google AI Studio Generative AI instance
  const ai = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  aiClient = ai.getGenerativeModel({ model: 'gemini-2.5-flash' });
} else {
  console.warn('⚠️ GEMINI_API_KEY environment variable is not defined. Falling back to local Mock AI generator.');
}

/**
 * Generates an outline based on a topic prompt
 */
exports.generateOutline = async (prompt, slideCount = 5) => {
  if (!aiClient) {
    return getMockOutline(prompt, slideCount);
  }

  try {
    const systemPrompt = `
      You are an expert presentation outline generator.
      You have been provided with detailed requirements by the user below, which may include the Title, specific requirements, a Target Audience Role (e.g., Student, Professor, Business Professional), and a Delivery Tone.
      
      USER REQUIREMENTS:
      """
      ${prompt}
      """
      
      CRITICAL INSTRUCTIONS:
      1. You MUST deeply tailor the vocabulary, complexity, and depth of the content to match the specified "Audience Role" and "Tone". 
         - If the audience is a "Student", use educational, simple explanations.
         - If "Professor", use highly academic, analytical language.
         - If "Business Professional", focus strictly on ROI, metrics, and actionable strategies.
      2. You must generate exactly ${slideCount} slides.
      3. You must respond with raw JSON ONLY. Do not include markdown blocks, backticks, or comments. The output must be directly parseable.
      
      JSON format structure:
      {
        "title": "A highly professional and clean title for the presentation deck",
        "slides": [
          {
            "title": "Slide Title",
            "content": [
              "Bullet point 1",
              "Bullet point 2",
              "Bullet point 3"
            ],
            "layout": "One of: 'title', 'bullets', 'columns', 'stats', 'timeline'",
            "icon": "A single Lucide React Icon name (e.g. 'Activity', 'Award', 'Briefcase', 'TrendingUp', 'Users', 'Database', 'Cloud', 'FileText', 'Presentation', 'Shield', 'Globe', 'Compass')",
            "note": "Informative speaker notes detailing the slide's contents and presentation tips."
          }
        ]
      }

      Choose layouts strategically:
      - 'title': Only use for the first slide (slide 1).
      - 'stats': Use if there is a primary percentage, fraction, or currency metric to call out.
      - 'columns': Use for side-by-side product comparisons or 3 pillars.
      - 'timeline': Use for milestone roadmaps or historical progression lists.
      - 'bullets': Standard slide format with 3-4 bullet points.
    `;

    const result = await aiClient.generateContent({
      contents: [{ role: 'user', parts: [{ text: systemPrompt }] }],
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: 0.7
      }
    });

    const responseText = result.response.text();
    const cleanJson = JSON.parse(responseText.trim());
    return cleanJson;
  } catch (error) {
    console.error('❌ Gemini Outline Generation Error:', error);
    // Graceful fallback to mock data on error so application doesn't crash
    return getMockOutline(prompt, slideCount);
  }
};

/**
 * Rewrites a slide content node based on helper commands
 */
exports.rewriteNodeText = async (text, command) => {
  if (!aiClient) {
    console.log(`🤖 [AI Mock] Rewriting text: "${text}" with command: "${command}"`);
    if (command === 'shorter') return `Summary: ${text.slice(0, 30)}...`;
    if (command === 'formal') return `Furthermore, it is established that: ${text}`;
    return `${text} (AI Enhanced)`;
  }

  try {
    const prompt = `
      You are an AI copywriting assistant inside a slide editor.
      Take the following text: "${text}"
      Rewrite it to be: "${command}" (e.g. 'shorter', 'more professional', 'action-oriented', 'enthusiastic').
      Respond with ONLY the rewritten text. Do not add quotes, introductions, or annotations.
    `;

    const result = await aiClient.generateContent(prompt);
    return result.response.text().trim();
  } catch (error) {
    console.error('❌ Gemini Rewrite Error:', error);
    return `${text} (AI Enhanced)`;
  }
};
